[~,I] = min(TotalMinMass);
% I = 6
I = 1
[net_power,cyc_efficiency,D_T,D_c,Ma_T,Ma_c,Anozzle,q_reactor,...
    q_rad,T1,Power_T,Power_c,HEXeffect,energy,p1,T2,p2,T3,p3,~,p4,T5,...
    p5,T6,p6,~,Vratio] = BraytonCycle(m_dot(I),9000,T4(I),2,UA(I),...
    A_panel(I),200,'CO2',2,1)